services:
  - type: web
    name: encrypted-news-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn wrapper_server:app --host 0.0.0.0 --port 3000
    plan: free
